[ids]
*

[main]
# Tap = Escape, Hold = nav layer
capslock = overload(nav, esc)

[nav]
i = up
k = down
j = left
l = right

n = C-left
m = C-right

b = C-S-left
w = C-S-right

f = backspace

a = C-a
y = C-c
p = C-v
x = C-x

c = C-backspace
v = C-delete

